on: workflow_dispatch

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:    
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/4f28e852-45ad-4543-8a9e-fab850b8d253
